### ISSUE TITLE
Does only work with HTTPS URLs if they don't end with .git

### ISSUE THREAD

**Issue by kwin** [morgant/finishGoogleCodeGitHubWikiMigration#3]
Maybe you can extend the readme to also give an example on how to use that with HTTPS URLs.
I tried `https://github.com/kwin/cppcheclipse.git`. This failed with the exception 

```
Cloning 'kwin/cppcheclipse'... Done.
Cloning 'kwin/cppcheclipse.wiki'... remote: Repository not found.
fatal: repository 'https://github.com/kwin/cppcheclipse.git.wiki/' not found
Error!
Exiting.
```

although I did create a wiki beforehand and added a page to it.

Only after modifying the parameter to `https://github.com/kwin/cppcheclipse`(without the .git extension) it did work. Please at least add a hint in the readme or in the best case also accept the parameter with the .git extension (as that is the clone URL being given by github itself).

**Comment by morgant** [comment]
@kwin Thanks for pointing this out. This was a bug in the regex that matched HTTPS clone URLs and I've fixed this in the latest release. I did also clarify the README with regards to using HTTPS clone URLS, since that wasn't mentioned at all.
